name: setup-ios-shorebird
description: setup-ios-shorebird
inputs:
  p12_password:
    required: true
  shorebird_token:
    required: true 
runs:
  using: "composite"
  steps:
    - uses: subosito/flutter-action@v2
      with:
        flutter-version-file: pubspec.yaml
        channel: "stable"
        cache: true
    - uses: shorebirdtech/setup-shorebird@v1
      with:
        cache: true
      env:
        SHOREBIRD_TOKEN: ${{ inputs.shorebird_token }}    
    - shell: bash 
      env:
        P12_PASSWORD: ${{ inputs.p12_password }}
      run: |
         mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
         cp ios/*.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
         security create-keychain -p "" build.keychain
         security default-keychain -s build.keychain
         security unlock-keychain -p "" build.keychain
         security import ios/certificate.p12 -k build.keychain -P "$P12_PASSWORD" -A -t cert -f pkcs12
         security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
         security find-identity -v -p codesigning   
    - run: flutter pub get
      shell: bash
    - run: |
        cd ios
        pod install
      shell: bash