name: shorebird-android-patch
description: shorebird-android-patch
inputs:
  KEYSTORE_BASE64:
    required: true
  KEYSTORE_PASSWORD:
    required: true
  KEY_PASSWORD:
    required: true
  KEY_ALIAS:
    required: true  
outputs:
  build_type:
    value: ${{ steps.set_output.outputs.build_type }}
runs:
  using: "composite"
  steps:
      - shell: bash 
        run: |
          flavor="${{ github.ref_name }}"
          TARGET_ID="${{ inputs.shorebird_app_id }}"
          sed -i "s/^app_id:.*/app_id: $TARGET_ID/" shorebird.yaml
          shorebird patch android \
          --release-version=latest \
          --flavor=$flavor \
          --dart-define=ENV=$flavor \
          --no-tree-shake-icons
      
  




