name: shorebird-android-patch
description: shorebird-android-patch
inputs:
  flavor:
    required: true
runs:
  using: "composite"
  steps:
      - shell: bash 
        run: |
          shorebird patch android \
          --release-version=latest \
          --flavor=$flavor \
          --dart-define=ENV=$flavor \
          -- \
          --no-tree-shake-icons