name: set-shorebird-app-id
description: set-shorebird-app-id
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        BRANCH_NAME="${{ github.ref_name }}"
        echo "Current Branch / Environment: $BRANCH_NAME"
        if [ ! -f "shorebird.yaml" ]; then
          echo "::error::shorebird.yaml not found in root directory!"
          exit 1
        fi
        TARGET_ID=$(grep -A 2 'flavors:' shorebird.yaml | grep "  $BRANCH_NAME:" | awk '{print $2}')
        if [ -z "$TARGET_ID" ]; then
          echo "::error::Could not find app_id for flavor '$BRANCH_NAME' in shorebird.yaml"
          exit 1
        fi
        echo "Found App ID for $BRANCH_NAME: $TARGET_ID"
        if [ "$(uname)" == "Darwin" ]; then
          sed -i '' "s/^app_id:.*/app_id: $TARGET_ID/" shorebird.yaml
        else
          sed -i "s/^app_id:.*/app_id: $TARGET_ID/" shorebird.yaml
        fi
        echo "Successfully updated root app_id in shorebird.yaml!"