name: "Test Core Action"
description: "Test connecting to core action"
inputs:
  shorebird-token:
    required: true  
  github-token:
    required: true
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v6
        with:
               fetch-depth: 1
      - uses: actions/checkout@v4
        with:
          repository: HishamKoptaN/flutter-devops-core
          token: ${{ inputs.github-token }}
          path: actions/core/setup-flutter
      - uses: HishamKoptaN/flutter-devops-core/actions/core/setup-flutter@v5
      #- uses: HishamKoptaN/flutter-devops-core/actions/core/setup-shorebird
      #- uses: HishamKoptaN/flutter-devops-core/actions/android/android-signing
      #  with:
      #    flavor: ${{ github.ref_name }}
      #- uses: actions/cache@v4
      #  with:
      #    path: build/
      #    key: ${{ runner.os}}-${{ github.ref_name }}    
      #- id: dry_run
      #  uses: ./actions/android/shorebird-android-dry-patch
      #- if: ${{ steps.dry_run.outputs.build_type == 'patch' }}
      #  uses: ./actions/android/shorebird-android-patch
      #  with:
      #    flavor: ${{ github.ref_name }}
      #- if: ${{ steps.dry_run.outputs.build_type == 'release'}}
      #  uses: ./actions/android/shorebird-android-release
      #  with:
      #    google_play_service_account_json: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
      #    track: internal
      #- if: ${{ steps.dry_run.outputs.build_type == 'release'}}
      #  uses: ./actions/android/shorebird-android-apk-release
      #  with:
      #    github_token: ${{ inputs.github-token }}