name: setup-ios-shorebird
description: setup-ios-shorebird
inputs:
  p12_password:
    required: true
  shorebird_token:
    required: true 
runs:
  using: "composite"
  steps:
    - uses: HishamKoptaN/flutter-devops-core/.github/actions/core/setup-shorebird@prod
    - run: flutter pub get
      shell: bash
    - run: |
        cd ios
        pod install
      shell: bash