name: setup-flutter
description: "Cache Flutter pub dependencies to speed up builds"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-${{ hashFiles('**/pubspec.lock')}} 
    - uses: subosito/flutter-action@v2
      with:
        flutter-version-file: pubspec.yaml
        channel: "stable"
        cache: true

        