name: shorebird-android-apk-release
description: shorebird-android-apk-release
inputs:
  github_token:
    required: true
runs:
  using: "composite"
  steps:
      - id: get-build-version
        uses: HishamKoptaN/flutter-devops-core/actions/core/get-build-version@v1
        with:
          platform: "android"
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: false
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'false'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - shell: bash 
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.caching=false -Dorg.gradle.vfs.watch=false"
        working-directory: ${{ github.workspace }}
        run: |
            shorebird release android \
            --target=lib/main.dart \
            --artifact=apk \
            --confirm \
            --flutter-version=3.47.4 \
            --flavor=${{ github.ref_name }} \
            --dart-define=ENV=${{ github.ref_name }} \
            --build-name=${{ steps.get-build-version.outputs.build_name }} \
            --build-number=${{ steps.get-build-version.outputs.build_number }} \
            -- \
            --no-tree-shake-icons
      - uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-${{ github.ref_name }}-release.apk
          tag_name: v${{ steps.get-build-version.outputs.build_name }}+${{ steps.get-build-version.outputs.build_number }}
          name: ${{ steps.get-build-version.outputs.build_name }}+${{ steps.get-build-version.outputs.build_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ inputs.github_token }}




