name: shorebird-android-apk-release
description: shorebird-android-apk-release
inputs:
  github_token:
    required: true
runs:
  using: "composite"
  steps:
      - shell: bash 
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo docker image prune --all --force
      - id: get-build-version
        uses: HishamKoptaN/flutter-devops-core/actions/core/get-build-version@v1
        with:
          platform: "android"
      - shell: bash 
        run: |
            shorebird release android \
            --target=lib/main.dart \
            --artifact=apk \
            --confirm \
            --flutter-version=3.47.4 \
            --flavor=${{ github.ref_name }} \
            --dart-define=ENV=${{ github.ref_name }} \
            --build-name=${{ steps.get-build-version.outputs.build_name }} \
            --build-number=${{ steps.get-build-version.outputs.build_number }} \
            -- \
            --no-tree-shake-icons
      - uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-${{ github.ref_name }}-release.apk
          tag_name: v${{ steps.get-build-version.outputs.build_name }}+${{ steps.get-build-version.outputs.build_number }}
          name: ${{ steps.get-build-version.outputs.build_name }}+${{ steps.get-build-version.outputs.build_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ inputs.github_token }}




