name: Build Web

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: HishamKoptaN/flutter-devops-core/.github/actions/core/setup-flutter@prod
      - run: flutter pub get
      - run: flutter build web --release --dart-define=ENV=${{ inputs.flavor }}
      - uses: actions/upload-artifact@v4
        with:
          name: web-app-${{ inputs.flavor }}
          path: build/web/**
          retention-days: 1
