name: 60-stores-layer.yml

on:
  workflow_dispatch:
  workflow_call:
jobs:
  shorebird-release-placeholder:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4