name: get-build-version
description: get-build-version with smart collision & flutter version check loop

inputs:
  platform:
    type: string
    required: true
  shorebird_app_id:
    required: true
outputs:
  build_name:
    value: ${{ steps.version_calculator.outputs.BUILD_NAME }}
  build_number:
    value: ${{ steps.version_calculator.outputs.BUILD_NUMBER }}
runs:
  using: "composite"
  steps:
    - id: version_calculator
      shell: bash
      run: |
        
       
          
          current_flutter_version=$(flutter --version | head -n 1 | awk '{print $2}')
          latest_full_version=$(echo "$raw_list" | head -n 1 | awk '{print $2}' || echo "1.0.0+1")
          

        echo "Calculated Build Name: $BUILD_NAME"
        echo "Calculated Build Number: $BUILD_NUMBER"
        echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_OUTPUT
        echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_OUTPUT