// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-MLFhwlNtWEhhiR8xdoOxJGVsm3NjYxo',
    appId: '1:296117455905:web:60ef2a7314435b43816760',
    messagingSenderId: '296117455905',
    projectId: 'flutter-devops-core-dev',
    authDomain: 'flutter-devops-core-dev.firebaseapp.com',
    storageBucket: 'flutter-devops-core-dev.firebasestorage.app',
    measurementId: 'G-LZYTW15172',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQdlFpJQuq82qdDuQ_KiKC7SC3Hh1wFpc',
    appId: '1:296117455905:android:428b7289c2da1eaa816760',
    messagingSenderId: '296117455905',
    projectId: 'flutter-devops-core-dev',
    storageBucket: 'flutter-devops-core-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-utqTscCAF7yGusqg_-9P1bNiDQ6OGk0',
    appId: '1:296117455905:ios:acbc55b342d379bd816760',
    messagingSenderId: '296117455905',
    projectId: 'flutter-devops-core-dev',
    storageBucket: 'flutter-devops-core-dev.firebasestorage.app',
    iosBundleId: 'com.example.flutterDevopsCore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-utqTscCAF7yGusqg_-9P1bNiDQ6OGk0',
    appId: '1:296117455905:ios:acbc55b342d379bd816760',
    messagingSenderId: '296117455905',
    projectId: 'flutter-devops-core-dev',
    storageBucket: 'flutter-devops-core-dev.firebasestorage.app',
    iosBundleId: 'com.example.flutterDevopsCore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-MLFhwlNtWEhhiR8xdoOxJGVsm3NjYxo',
    appId: '1:296117455905:web:9e2472f685f2ad48816760',
    messagingSenderId: '296117455905',
    projectId: 'flutter-devops-core-dev',
    authDomain: 'flutter-devops-core-dev.firebaseapp.com',
    storageBucket: 'flutter-devops-core-dev.firebasestorage.app',
    measurementId: 'G-YWFYNC3WZR',
  );
}
