name: shorebird-ios-dry-patch
description: shorebird-ios-dry-patch
inputs:
  flavor:
    required: true
  shorebird_token:
    required: true
  p12_password:
    required: true
  appstore_issuer_id:
    required: true
  appstore_api_key_id:
    required: true
  appstore_api_private_key:
    required: true
outputs:
  build_type:
    value: ${{ steps.set_output.outputs.build_type }}
runs:
  using: "composite"
  steps:
    - uses: HishamKoptaN/flutter-devops-core/.github/actions/core/setup-flutter@prod
    - uses: HishamKoptaN/flutter-devops-core/.github/actions/core/setup-shorebird@prod
      with:
        shorebird_token: ${{ inputs.shorebird_token }}   
    - uses: HishamKoptaN/flutter-devops-core/.github/actions/ios/setup-ios-signing@prod
      with:
        p12-password: ${{ inputs.p12_password }}
        appstore_issuer_id: ${{ inputs.appstore_issuer_id }}
        appstore_api_key_id: ${{ inputs.appstore_api_key_id }}
        appstore_api_private_key: ${{ inputs.appstore_api_private_key }}
    - id: dry_run
      env:
        SHOREBIRD_TOKEN: ${{ inputs.shorebird_token }}
      shell: bash
      run: |
       if shorebird patch ios \
       --release-version=latest \
       --export-options-plist=ios/ExportOptions.plist \
       --flavor="${{ inputs.flavor }}" \
       --dart-define=ENV=prod \
       --dry-run; then
          echo "dry_run_status=success" >> $GITHUB_OUTPUT
        else
          echo "dry_run_status=failed" >> $GITHUB_OUTPUT
        fi
      continue-on-error: true
    - id: set_output
      shell: bash
      run: |
        STATUS="${{ steps.dry_run.outputs.dry_run_status }}"
        if [ "$STATUS" == "success" ]; then
          echo "build_type=patch" >> $GITHUB_OUTPUT
        else
          echo "build_type=release" >> $GITHUB_OUTPUT
        fi