name: shorebird-android-release
description: shorebird-android-release
inputs:
  google_play_service_account_json:
    required: true
  track:
    type: string
    required: true
runs:
  using: "composite"
  steps:
      - uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'false'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - id: get-build-version
        uses: ./actions/core/get-build-version
        with:
          platform: "android"
      - shell: bash
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=true -Dorg.gradle.caching=true -Dorg.gradle.vfs.watch=true"
        run: |
            shorebird release android \
            --confirm \
            --flutter-version=3.47.4 \
            --flavor=${{ github.ref_name }} \
            --dart-define=ENV=${{ github.ref_name }} \
            --build-name=${{ steps.get-build-version.outputs.build_name }} \
            --build-number=${{ steps.get-build-version.outputs.build_number }} \
            -- \
            --no-tree-shake-icons
      - id: upload-play
        uses: r0adkll/upload-google-play@v1
        with:
          packageName: com.greensouq.app
          serviceAccountJsonPlainText: ${{ inputs.google_play_service_account_json }}
          releaseFiles: build/app/outputs/bundle/prodRelease/app-prod-release.aab
          tracks: ${{ inputs.track }}
          status: completed
          changesNotSentForReview: false
          inAppUpdatePriority: 5
      
  




