// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAlObUhG71c_fxb-bOkJJR3ogDbDh1Mw5Y',
//     appId: '1:138886686943:web:40aa979fac2eb5d4d0a16a',
//     messagingSenderId: '138886686943',
//     projectId: 'abujena-dawajen-dev-dba46',
//     authDomain: 'abujena-dawajen-dev-dba46.firebaseapp.com',
//     storageBucket: 'abujena-dawajen-dev-dba46.firebasestorage.app',
//     measurementId: 'G-VWY7R5L170',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCDqAnNQcaxy31LhVGOR5yYgn8nGO7luGk',
//     appId: '1:138886686943:android:3fec89a1dfd57306d0a16a',
//     messagingSenderId: '138886686943',
//     projectId: 'abujena-dawajen-dev-dba46',
//     storageBucket: 'abujena-dawajen-dev-dba46.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDrwv-A8P8EUAF1z2GHoQNg3caoVjFkfs0',
//     appId: '1:138886686943:ios:610dd344e7ff7bfad0a16a',
//     messagingSenderId: '138886686943',
//     projectId: 'abujena-dawajen-dev-dba46',
//     storageBucket: 'abujena-dawajen-dev-dba46.firebasestorage.app',
//     iosBundleId: 'com.abujena.dawajen',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDrwv-A8P8EUAF1z2GHoQNg3caoVjFkfs0',
//     appId: '1:138886686943:ios:610dd344e7ff7bfad0a16a',
//     messagingSenderId: '138886686943',
//     projectId: 'abujena-dawajen-dev-dba46',
//     storageBucket: 'abujena-dawajen-dev-dba46.firebasestorage.app',
//     iosBundleId: 'com.abujena.dawajen',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAlObUhG71c_fxb-bOkJJR3ogDbDh1Mw5Y',
//     appId: '1:138886686943:web:7d96f0a57e3650e1d0a16a',
//     messagingSenderId: '138886686943',
//     projectId: 'abujena-dawajen-dev-dba46',
//     authDomain: 'abujena-dawajen-dev-dba46.firebaseapp.com',
//     storageBucket: 'abujena-dawajen-dev-dba46.firebasestorage.app',
//     measurementId: 'G-RSWJ53C88F',
//   );
// }
