name: shorebird-android-dry-patch
description: "Checks if Shorebird patch is viable using dry-run"
outputs:
  build_type:
    value: ${{ steps.set_output.outputs.build_type }}
runs:
  using: "composite"
  steps:
    - id: dry_run
      shell: bash
      run: |
       if shorebird patch android \
       --release-version=latest \
       --flavor="${{ github.ref_name }}" \
       --dry-run; then
          echo "dry_run_status=success" >> $GITHUB_OUTPUT
        else
          echo "dry_run_status=failed" >> $GITHUB_OUTPUT
        fi
    - id: set_output
      shell: bash
      run: |
        STATUS="${{ steps.dry_run.outputs.dry_run_status }}"
        if [ "$STATUS" == "success" ]; then
          echo "build_type=patch" >> $GITHUB_OUTPUT
        else
          echo "build_type=release" >> $GITHUB_OUTPUT
        fi