name: shorebird-android-dry-patch
description: "Checks if Shorebird patch is viable using dry-run"
inputs:
  platform:
    type: string
    required: true
  shorebird_token:
    description: "Shorebird Secret Token"
    required: true
outputs:
  build_type:
    value: ${{ steps.set_output.outputs.build_type }}
runs:
  using: "composite"
  steps:
    - uses: HishamKoptaN/flutter-devops-core/.github/actions/core/setup-shorebird@prod
    - id: dry_run
      shell: bash
      env:
        SHOREBIRD_TOKEN: ${{ inputs.shorebird_token }}
      run: |
       if shorebird patch ${{ inputs.platform }} --flavor="${{ github.ref_name }}" --dry-run; then
          echo "dry_run_status=success" >> $GITHUB_OUTPUT
        else
          echo "dry_run_status=failed" >> $GITHUB_OUTPUT
        fi
      continue-on-error: true
    - id: set_output
      shell: bash
      run: |
        STATUS="${{ steps.dry_run.outputs.dry_run_status }}"
        if [ "$STATUS" == "success" ]; then
          echo "build_type=patch" >> $GITHUB_OUTPUT
        else
          echo "build_type=release" >> $GITHUB_OUTPUT
        fi