// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBSU55T6onovBWjpMD1CF8GuuE8lmRpaUU',
//     appId: '1:370986284193:web:03c3f855469a5ecabbace0',
//     messagingSenderId: '370986284193',
//     projectId: 'abujena-dawajen',
//     authDomain: 'abujena-dawajen.firebaseapp.com',
//     storageBucket: 'abujena-dawajen.firebasestorage.app',
//     measurementId: 'G-P3PREW8K0E',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAVxe9bEMWnkMcOZPu2tDA4YANRa_3wIaM',
//     appId: '1:370986284193:android:2627bbb75f61bd6cbbace0',
//     messagingSenderId: '370986284193',
//     projectId: 'abujena-dawajen',
//     storageBucket: 'abujena-dawajen.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyA2fF4ndpBMsJX5jqEI4tEzceTEiK_31xE',
//     appId: '1:370986284193:ios:97c65da54975ffddbbace0',
//     messagingSenderId: '370986284193',
//     projectId: 'abujena-dawajen',
//     storageBucket: 'abujena-dawajen.firebasestorage.app',
//     iosBundleId: 'com.abujena.dawajen',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyA2fF4ndpBMsJX5jqEI4tEzceTEiK_31xE',
//     appId: '1:370986284193:ios:97c65da54975ffddbbace0',
//     messagingSenderId: '370986284193',
//     projectId: 'abujena-dawajen',
//     storageBucket: 'abujena-dawajen.firebasestorage.app',
//     iosBundleId: 'com.abujena.dawajen',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBSU55T6onovBWjpMD1CF8GuuE8lmRpaUU',
//     appId: '1:370986284193:web:8da80824aa054440bbace0',
//     messagingSenderId: '370986284193',
//     projectId: 'abujena-dawajen',
//     authDomain: 'abujena-dawajen.firebaseapp.com',
//     storageBucket: 'abujena-dawajen.firebasestorage.app',
//     measurementId: 'G-99G97TR0WS',
//   );
// }
