name: android-signing
description: android-signing
inputs:
  KEYSTORE_BASE64:
    required: true
  KEYSTORE_PASSWORD:
    required: true
  KEY_PASSWORD:
    required: true
  KEY_ALIAS:
    required: true  
runs:
  using: "composite"
  steps:
      - shell: bash 
        run: |
          echo "${{ inputs.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keyStoreProd.jks
      - shell: bash 
        run: |
          cat > android/key.properties << EOF
          storePassword=${{ inputs.KEYSTORE_PASSWORD }}
          keyPassword=${{ inputs.KEY_PASSWORD }}
          keyAlias=${{ inputs.KEY_ALIAS }}
          storeFile=keyStoreProd.jks
          EOF   