name: android-signing
description: android-signing
inputs:
  FLAVOR:
   required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        sed -i 's|^storeFile=.*|storeFile=${{ inputs.FLAVOR }}/keyStore.jks|' android/key.properties