name: main
env:
  force_javascript_actions_to_node24: true
  actions_allow_use_unsecure_node_version: true
permissions:
  contents: write
on:
  workflow_call:
    inputs:
      shorebird_app_id:
        type: string
        required: true
    secrets:
      FIREBASE_ADMIN_SDK:
        required: false
      SHOREBIRD_TOKEN:
        required: false
      FIREBASE_TOKEN:
        required: false
      GOOGLE_PLAY_SERVICE_ACCOUNT_JSON:
        required: false
      P12_PASSWORD:
        required: false
  push:
    branches: [dev, prod]
  workflow_dispatch:
jobs: 
  shorebird_layer:
    uses: ./.github/workflows/20-shorebird-layer.yml
    with:
      shorebird_app_id : ${{ inputs.shorebird_app_id }}
    secrets: inherit
  distribution_layer:
    needs: [shorebird_layer]
    if: always()
    uses: ./.github/workflows/50-distribution-layer.yml 
    secrets: inherit