name: Test CI/CD Pipeline

on:
  push:
    branches: [prod]
  workflow_dispatch:
    inputs:
      flavor:
        type: string
        default: 'dev'
        description: 'Flavor to test'
      platforms:
        type: string
        default: 'android,windows'
        description: 'Platforms to build: android,windows'

permissions:
  contents: write

jobs:
  workflows:
    uses: ./.github/workflows/00-core-main.yml
    with:
      flavor: ${{ inputs.flavor || 'dev' }}
      platforms: ${{ inputs.platforms || 'android,windows' }}
    secrets: inherit
