name: main

on:
  workflow_call:
  push:
    branches: [dev, prod]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: HishamKoptaN/flutter-devops-core
          ref: prod
          token: ${{ secrets.GITHUB_TOKEN }}
          path: temp-core-actions
      - uses: ./temp-core-actions/.github/actions/core/setup-flutter
      - uses: ./temp-core-actions/.github/actions/core/setup-shorebird
      - uses: ./temp-core-actions/.github/actions/android/shorebird-android-release