name: CI/CD Pipeline #2
on:
    push:
        branches: [ prod ]
    workflow_dispatch:
permissions:
    contents: write
jobs:
    deploy:
      runs-on: ubuntu-latest
      environment: ${{ github.ref_name }}
      env: 
        SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
      steps:
        - uses: actions/checkout@v4
        - uses: HishamKoptaN/flutter-devops-core@v1