name: Build iOS

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter pub get

      - run: flutter build ios --release --flavor=${{ inputs.flavor }} --dart-define=ENV=${{ inputs.flavor }} --no-codesign

      - uses: actions/upload-artifact@v4
        with:
          name: ios-app-${{ inputs.flavor }}
          path: build/ios/iphoneos/**/*.app
          retention-days: 1
