name: 20-shorebird-ios.yml

on:
  workflow_call:
    inputs:
      shorebird_app_id:
        type: string
        required: true
jobs:
  check:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
    outputs:
      build_type: ${{ steps.dry_run.outputs.build_type }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          if [ -z "${{ secrets.P12_PASSWORD }}" ]; then
            echo "TRACING ERROR: ${{ secrets.P12_PASSWORD }} is empty in File 2 (20-shorebird-ios.yml)!"
            exit 1
          else
            echo "TRACING SUCCESS: ${{ secrets.P12_PASSWORD }} is alive in File 2 (length: ${#P12_PASSWORD})"
          fi
      - uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true 
      - id: dry_run
        uses: HishamKoptaN/flutter-devops-core/.github/actions/shorebird-dry-patch@prod
        with:
          platform: 'ios'
          shorebird_token: ${{ secrets.SHOREBIRD_TOKEN }}
  shorebird_ios_patch:
    needs: check
    if: ${{ needs.check.outputs.build_type == 'patch' }}
    uses: ./.github/workflows/20-shorebird-ios-patch.yml
    with:
      shorebird_app_id: ${{ inputs.shorebird_app_id }}
    secrets: inherit
  shorebird_ios_release:
    needs: check
    if: ${{ needs.check.outputs.build_type == 'release' }}
    uses: ./.github/workflows/30-shorebird-ios-release_prod.yml
    with:
      shorebird_app_id: ${{ inputs.shorebird_app_id }}
    secrets: inherit