name: 20-shorebird-android
on:
  workflow_call:
jobs:
  check:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
    outputs:
      build_type: ${{ steps.dry_run.outputs.build_type }}
    steps:
      - uses: actions/checkout@v6
        with:
         fetch-depth: 0
      - uses: actions/checkout@v4
        with:
          repository: HishamKoptaN/flutter-devops-core
          ref: prod
          token: ${{ secrets.GITHUB_TOKEN }}
          path: temp-core-actions
      - uses: temp-core-actions/.github/actions/core/setup-flutter
      - uses: temp-core-actions/.github/actions/core/setup-shorebird
        if: hashFiles('android/app/keyStore.jks') != ''
      - uses: temp-core-actions/.github/actions/android/android-signing
        with:
          flavor: ${{ github.ref_name }}
      - uses: actions/cache@v4
        with:
          path: build/
          key: ${{ runner.os}}-${{ github.ref_name }}    
      - shell: bash
        run: |
         sed -i "s/^app_id:.*/app_id: "${{ vars.SHOREBIRD_APP_ID }}"/" shorebird.yaml   
      - id: dry_run
        uses: temp-core-actions/.github/actions/android/shorebird-android-dry-patch
      - if: ${{ steps.dry_run.outputs.build_type == 'patch' }}
        uses: temp-core-actions/.github/actions/android/shorebird-android-patch
        with:
          flavor: ${{ github.ref_name }}
      - if: ${{ steps.dry_run.outputs.build_type == 'release'}}
        uses: temp-core-actions/.github/actions/android/shorebird-android-release
        with:
          google_play_service_account_json: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          track: internal
      - if: ${{ steps.dry_run.outputs.build_type == 'release'}}
        uses: temp-core-actions/.github/actions/android/shorebird-android-apk-release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}