name: 20-shorebird-android-patch.yml
on:
  workflow_call:
    inputs:
      shorebird_app_id:
        type: string
        required: true  
    outputs:
      changed:
        value: ${{ jobs.patch.outputs.changed }}
    secrets:
      SHOREBIRD_TOKEN:
        required: false

jobs:
  patch:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    outputs:
      changed: ${{ steps.verify.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: HishamKoptaN/flutter-devops-core/.github/actions/setup-android-shorebird@prod
      - run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/muein_orders.jks
      - run: |
          cat > android/key.properties << EOF
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=muein_orders.jks
          EOF   
      - id: extract_flutter
        shell: bash
        run: bash ${{ github.action_path }}/../../scripts/get-flutter-version.sh
      - id: verify
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
        continue-on-error: true
        run: |
          flavor="${{ github.ref_name }}"
          TARGET_ID="${{ inputs.shorebird_app_id }}"
          FLUTTER_VER="${{ steps.extract_flutter.outputs.version }}"
          sed -i "s/^app_id:.*/app_id: $TARGET_ID/" shorebird.yaml
          echo "Setting Shorebird Flutter version to $FLUTTER_VER..."
          shorebird flutter versions use $FLUTTER_VER
          if shorebird patch android \
          --flavor=$flavor \
          --release-version=latest \
          --dart-define=ENV=$flavor '--' --no-tree-shake-icons; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            exit 1
          fi
      - if: always()
        run: rm -f android/app/muein_orders.jks android/key.properties