name: Shorebird Layer

on:
  workflow_call:
    inputs:
      shorebird_app_id:
        type: string
        required: true
jobs:
  android:
   uses: ./.github/workflows/20-shorebird-android.yml
   secrets: inherit
  # ios:
  #   uses: ./.github/workflows/20-shorebird-ios.yml
  #   secrets: inherit