name: 20-shorebird-android-apk-release
on:
  workflow_call:
jobs:
  check:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
    outputs:
      build_type: ${{ steps.dry_run.outputs.build_type }}
    steps:
      - uses: actions/checkout@v6
        with:
         fetch-depth: 1
      - uses: ./actions/core/setup-flutter

      - uses: ./actions/core/setup-shorebird
        if: hashFiles('android/app/keyStore.jks') != ''

      - uses: ./actions/android/android-signing
        with:
          flavor: ${{ github.ref_name }}

      - uses: actions/cache@v4
        with:
          path: build/
          key: ${{ runner.os}}-${{ github.ref_name }}    

      - id: dry_run
        uses: ./actions/android/shorebird-android-dry-patch

      - if: ${{ steps.dry_run.outputs.build_type == 'patch' }}
        uses: ./actions/android/shorebird-android-patch
        with:
          flavor: ${{ github.ref_name }}

      - if: ${{ steps.dry_run.outputs.build_type == 'release'}}
        uses: ./actions/android/shorebird-android-apk-release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}