name: 20-shorebird-ios-release_dev.yml
on:
  workflow_call:
    inputs:
      shorebird_app_id:
        type: string
        required: true
jobs:
  ios:
    runs-on: macos-latest
    env:
      SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
      P12_PASSWORD: "163200"
    steps:
      - uses: actions/checkout@v4
      - id: get-build-version
        uses: HishamKoptaN/flutter-devops-core/.github/actions/get-build-version@prod
        with:
          platform: "ios"
          shorebird_app_id: ${{ inputs.shorebird_app_id }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.7"
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: cd ios && pod install
      - run: ls -la *.p12 *.mobileprovision
      - run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp muein_orders_appstore_prod.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
          security create-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
          security list-keychains -s build.keychain
          security find-identity -v -p codesigning
      - run: |
          shorebird release ios --flavor=prod
