name: 20-shorebird-ios.yml
on:
  workflow_call:
jobs:
  check:
    runs-on: macos-latest
    environment: ${{ github.ref_name }}
    env:
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ vars.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_API_KEY_ID: ${{ vars.APP_STORE_CONNECT_API_KEY_ID }}
      APP_STORE_CONNECT_API_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}
    outputs:
      build_type: ${{ steps.dry_run.outputs.build_type }}
    steps:
      - uses: actions/checkout@v6
      # - uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~/.cocoapods
      #       ios/Pods
      #     key: pods-${{ runner.os }}-${{ hashFiles('ios/Podfile.lock') }}
      - id: dry_run
        uses: HishamKoptaN/flutter-devops-core/.github/actions/ios/shorebird-ios-dry-patch@prod
        with:
          flavor : ${{ github.ref_name }}
          shorebird_token: ${{ secrets.SHOREBIRD_TOKEN }}
          p12_password: ${{ secrets.P12_PASSWORD }}
          appstore_issuer_id: ${{ vars.APP_STORE_CONNECT_ISSUER_ID }}
          appstore_api_key_id: ${{ vars.APP_STORE_CONNECT_API_KEY_ID }}
          appstore_api_private_key: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}
  shorebird_ios_patch:
    needs: check
    if: ${{ needs.check.outputs.build_type == 'patch' }}
    uses: ./.github/workflows/20-shorebird-ios-patch.yml
    secrets: inherit
  shorebird_ios_release:
    needs: check
    if: ${{ needs.check.outputs.build_type == 'release' }}
    uses: ./.github/workflows/30-shorebird-ios-release_prod.yml
    secrets: inherit