name: 20-shorebird-android
on:
  workflow_call:
jobs:
  check:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
    outputs:
      build_type: ${{ steps.dry_run.outputs.build_type }}
    steps:
