name: 20-shorebird-ios-patch.yml

on:
  workflow_call:
    inputs:
      shorebird_app_id:
        type: string
        required: true  
jobs:
  patch:
    runs-on: macos-latest
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          channel: "stable"
          cache: true
      - uses: actions/cache@v4
        with:
          path: |
            build/
            ios/Pods
            ios/.symlinks
          key: ios-patch-${{ github.sha }}-macos
          restore-keys: ios-patch-macos-
      - run: flutter pub get
      - run: |
          cd ios
          pod install --repo-update
      - env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
        run: |
          shorebird patch ios \
            --dart-define=ENV=prod \
            --flavor=prod 
