name: 20-shorebird-ios-patch.yml

on:
  workflow_call:
jobs:
  patch:
    runs-on: macos-latest
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v6
      - uses: HishamKoptaN/flutter-devops-core/.github/actions/core/setup-flutter@prod
      - uses: HishamKoptaN/flutter-devops-core/.github/actions/core/setup-shorebird@prod
      - uses: HishamKoptaN/flutter-devops-core/.github/actions/ios/setup-ios-signing@prod
        with:
          p12-password: ${{ secrets.P12_PASSWORD }}
          appstore_issuer_id: ${{ vars.APP_STORE_CONNECT_ISSUER_ID }}
          appstore_api_key_id: ${{ vars.APP_STORE_CONNECT_API_KEY_ID }}
          appstore_api_private_key: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}
      - uses: HishamKoptaN/flutter-devops-core/.github/actions/core/setup-flutter@prod
      - uses: actions/cache@v4
        with:
          path: |
            build/
            ios/Pods
            ios/.symlinks
          key: ios-patch-${{ github.sha }}-macos
          restore-keys: ios-patch-macos-
      - run: flutter pub get
      - run: |
          cd ios
          pod install --repo-update
      - env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
        run: |
          shorebird patch ios \
          --export-options-plist=ios/ExportOptions.plist \
          --flavor="${{ github.ref_name }}" \
          --release-version=latest \
          --dart-define=ENV=${{ github.ref_name }} \
