name: 22-shorebird-android-release
on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
      shorebird_app_id:
        type: string
        required: true  
    outputs:
      changed:
        value: ${{ jobs.release.outputs.changed }}
    secrets:
      SHOREBIRD_TOKEN:
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.flavor }}
    outputs:
      changed: ${{ steps.run.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - id: run
        shell: bash
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
        run: |
          flavor="${{ inputs.flavor }}"
          TARGET_ID="${{ inputs.shorebird_app_id }}"
          sed -i "s/^app_id:.*/app_id: $TARGET_ID/" shorebird.yaml
          latest_version=$(shorebird releases list --app-id "$TARGET_ID" 2>/dev/null | grep 'android' | head -n 1 | awk '{print $2}')
          echo "Latest Android Version Found: '$latest_version'"
          if [ -z "$latest_version" ]; then
            BUILD_NAME="1.0.0"
            BUILD_NUMBER="1"
          else
            raw_base=$(echo "$latest_version" | cut -d'+' -f1)
            BUILD_NAME=$(echo "$raw_base" | cut -d'-' -f1)
            raw_build=$(echo "$latest_version" | grep -q '+' && echo "$latest_version" | cut -d'+' -f2 || echo "0")
            BUILD_NUMBER=$((raw_build + 1))
          fi
          echo "Build Name: $BUILD_NAME"
          echo "Build Number: $BUILD_NUMBER"
          if shorebird release android \
          --flavor=$flavor \
          --build-name=$BUILD_NAME \
          --build-number=$BUILD_NUMBER \
          --dart-define=ENV=$flavor \
          --artifact=apk \
          '--' --no-tree-shake-icons; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            exit 1
          fi

      - if: success()
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-${{ inputs.flavor }}
          path: build/app/outputs/**/*.apk
          retention-days: 1