name: Deploy Linux

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
      full_version:
        type: string
        required: true
      base_version:
        type: string
        required: true
      use_patch:
        type: boolean
        required: false
        default: false
    secrets:
      SHOREBIRD_TOKEN:
        required: false

jobs:
  linux:
    uses: ./.github/workflows/20-shorebird-linux.yml
    with:
      flavor: ${{ inputs.flavor }}
      full_version: ${{ inputs.full_version }}
      base_version: ${{ inputs.base_version }}
      use_patch: ${{ inputs.use_patch }}
    secrets:
      SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
