name: 30-shorebird-android-prod-release
on:
  workflow_call:
    inputs:
      shorebird_app_id:
        type: string
        required: true  
      track:
        required: false
        type: string
        default: "internal"
    secrets:
      SHOREBIRD_TOKEN:
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
     TRACK: ${{ inputs.track }} 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 
      - uses: HishamKoptaN/flutter-devops-core/.github/actions/setup-android-shorebird@prod
      - id: get-build-version
        uses: HishamKoptaN/flutter-devops-core/.github/actions/get-build-version@prod
        with:
          shorebird_app_id: ${{ inputs.shorebird_app_id }}
      - run: |
            shorebird release android \
            --flavor=${{ github.ref_name }} \
            --dart-define=ENV=${{ github.ref_name }} \
            --build-name=${{ steps.get-build-version.outputs.build_name }} \
            --build-number=${{ steps.get-build-version.outputs.build_number }} \
            --confirm
      - id: upload-play
        uses: r0adkll/upload-google-play@v1
        with:
          packageName: com.muein.orders
          releaseFiles: build/app/outputs/bundle/prodRelease/app-prod-release.aab
          track: ${{ env.TRACK }}
          status: ${{ env.TRACK == 'production' && 'completed' || 'draft' }}
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          