name: 30-shorebird-ios-release_prod.yml
on:
  workflow_call:
    inputs:
      shorebird_app_id:
        type: string
        required: true
jobs:
  ios:
    runs-on: macos-latest
    environment: ${{ github.ref_name }}
    env:
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v4
        with:
          path: ios/Pods
          key: ios-pods-${{ hashFiles('ios/Podfile.lock') }}-${{ runner.os }}
          restore-keys: |
            ios-pods-
      - uses: actions/cache@v4
        with:
          path: |
            build/
            .dart_tool/
          key: ${{ runner.os }}-flutter-build-${{ hashFiles('pubspec.lock') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-flutter-build-${{ hashFiles('pubspec.lock') }}-
            ${{ runner.os }}-flutter-build-
      - uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ${{ github.workspace }}/.dart_tool
          key: flutter-deps-ios-${{ hashFiles('pubspec.lock') }}-${{ runner.os }}
          restore-keys: flutter-deps-ios-   
      - uses: actions/cache@v4
        with:
          path: |
            ~/.config/shorebird
            ~/.shorebird
          key: shorebird-ios-${{ runner.os }}-${{ hashFiles('pubspec.lock', 'shorebird.yaml') }}
          restore-keys: shorebird-ios-${{ runner.os }}-
      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          channel: "stable"
          cache: true
      - uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true
      - shell: bash 
        run: |
          echo "=== 1. التحقق من وجود البروفايل في مجلد المشروع ==="
          if [ -f "ios/prod_app_store_profile.mobileprovision" ]; then
            echo "✔ الملف موجود في المشروع بنجاح."
          else
            echo "❌ خطأ: الملف غير موجود في مجلد ios/ تأكد من رفعه أو مساره!"
            exit 1
          fi
          echo "=== 2. إنشاء المجلد النظامي ونسخ الملف إليه ==="
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ios/prod_app_store_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          echo "=== 3. التأكد من نجاح النسخ في مجلد النظام ==="
          if [ -f ~/Library/MobileDevice/Provisioning\ Profiles/prod_app_store_profile.mobileprovision ]; then
            echo "✔ تم نسخ البروفايل بنجاح إلى المجلد النظامي للماك:"
            ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
          else
            echo "❌ فشل نسخ الملف للمجلد النظامي!"
            exit 1
          fi
           security create-keychain -p "" build.keychain
           security default-keychain -s build.keychain
           security unlock-keychain -p "" build.keychain
           security import ios/certificate.p12 -k build.keychain -P "$P12_PASSWORD" -A -t cert -f pkcs12
           security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
           security find-identity -v -p codesigning   
      - run: flutter pub get
        shell: bash
      - run: |
          cd ios
          pod install
        shell: bash
      - id: get-build-version
        uses: HishamKoptaN/flutter-devops-core/.github/actions/get-build-version@prod
        with:
            platform: "ios"
            shorebird_app_id: ${{ inputs.shorebird_app_id }}
      - run: |
              shorebird release ios \
              --flavor=${{ github.ref_name }} \
              --dart-define=ENV=${{ github.ref_name }} \
              --build-name=${{ steps.get-build-version.outputs.build_name }} \
              --build-number=${{ steps.get-build-version.outputs.build_number }} \
              --target=lib/main.dart \
              --export-options-plist=ios/ExportOptions.plist \
              --confirm
      - id: find_ipa
        run: |
            IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -n 1)
            echo "ipa_path=$IPA_PATH" >> $GITHUB_OUTPUT
      - uses: apple-actions/upload-testflight-build@v3
        with:
           app-path: ${{ steps.find_ipa.outputs.ipa_path }}
           issuer-id: ${{ vars.APP_STORE_CONNECT_ISSUER_ID }}
           api-key-id: ${{ vars.APP_STORE_CONNECT_API_KEY_ID }}
           api-private-key: ${{ vars.APP_STORE_CONNECT_API_PRIVATE_KEY }}







                # - uses: HishamKoptaN/flutter-devops-core/.github/actions/setup-ios-shorebird@prod
     #   with:
     #     p12_password: ${{ secrets.P12_PASSWORD }}
     #     shorebird_token: ${{ secrets.SHOREBIRD_TOKEN }}