name: 30-shorebird-android-release
on:
  workflow_call:
    inputs:
      shorebird_app_id:
        type: string
        required: true  
      track:
        required: false
        type: string
        default: "internal"
jobs:
  release-dev:
    if: ${{ github.ref_name == 'dev' }}
    uses: ./.github/workflows/30-shorebird-android-dev-release.yml
    with:
      shorebird_app_id: ${{ inputs.shorebird_app_id }}
    secrets: inherit
  release-prod:
    if: ${{ github.ref_name == 'prod' }}
    uses: ./.github/workflows/30-shorebird-android-prod-release.yml
    with:
      shorebird_app_id: ${{ inputs.shorebird_app_id }}
      track: ${{ inputs.track }}
    secrets: inherit







      #- uses: actions/cache@v4
      #  with:
      #    path: |
      #      /usr/local/lib/android/sdk
      #    key: android-sdk-${{ runner.os }}-${{ hashFiles('android/app/build.gradle.kts', 'android/build.gradle.kts') }}
      #    restore-keys: android-sdk-${{ runner.os }}-
      #- uses: actions/cache@v4
      #  with:
      #    path: |
      #      ~/.gradle/caches
      #      ~/.gradle/wrapper
      #      android/.gradle
      #    key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'android/gradle.properties') }}-${{ runner.os }}
      #    restore-keys: |
      #      gradle-${{ hashFiles('**/*.gradle*') }}-${{ runner.os }}-
      #      gradle-${{ runner.os }}-
      #- uses: actions/cache@v4
      #  with:
      #    path: |
      #      ~/.gradle/caches
      #      ~/.gradle/wrapper
      #    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      #    restore-keys: |
      #      ${{ runner.os }}-gradle-
      #- uses: actions/cache@v4
      #  with:
      #    path: |
      #      build/
      #      android/.gradle
      #      android/app/build
      #      .dart_tool/build
      #    key: build-${{ hashFiles('lib/**/*.dart', 'pubspec.lock') }}-${{ runner.os }}
      #    restore-keys: |
      #      build-${{ hashFiles('pubspec.lock') }}-${{ runner.os }}-
      #      build-${{ runner.os }}-