name: 30-shorebird-ios-release_prod.yml
on:
  workflow_call:
    inputs:
      shorebird_app_id:
        type: string
        required: true
jobs:
  ios:
    runs-on: macos-latest
    environment: ${{ github.ref_name }}
    env:
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: HishamKoptaN/flutter-devops-core/.github/actions/ios/setup-ios-signing@prod
        with:
          p12-password: ${{ secrets.P12_PASSWORD }}
      - uses: actions/cache@v4
        with:
          path: ios/Pods
          key: ios-pods-${{ hashFiles('ios/Podfile.lock') }}-${{ runner.os }}
          restore-keys: |
            ios-pods-
      - uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/swift-package-manager
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-pods-swift-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${- runner.os }}-pods-swift-   
      - uses: actions/cache@v4
        with:
          path: |
            build/
            .dart_tool/
          key: ${{ runner.os }}-flutter-build-${{ hashFiles('pubspec.lock') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-flutter-build-${{ hashFiles('pubspec.lock') }}-
            ${{ runner.os }}-flutter-build-
      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          channel: "stable"
          cache: true
      - uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cocoapods
            ~/Library/Caches/CocoaPods
            ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-cocoapods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cocoapods-   
      - run: |
          rm -rf ~/Library/Caches/org.swift.swiftpm
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          rm -rf ios/SourcePackages
          rm -rf ~/Library/Caches/com.apple.dt.Xcode           
      - run: flutter pub get
        shell: bash
      - run: |
          cd ios
          pod install
        shell: bash
      - id: get-build-version
        uses: HishamKoptaN/flutter-devops-core/.github/actions/core/get-build-version@prod
        with:
            platform: "ios"
            shorebird_app_id: ${{ inputs.shorebird_app_id }}
      - run: |
              shorebird release ios \
              --flutter-version=3.44.7 \
              --flavor=${{ github.ref_name }} \
              --dart-define=ENV=${{ github.ref_name }} \
              --build-name=${{ steps.get-build-version.outputs.build_name }} \
              --build-number=${{ steps.get-build-version.outputs.build_number }} \
              --target=lib/main.dart \
              --export-options-plist=ios/ExportOptions.plist \
              --confirm
      - id: find_ipa
        run: |
            IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -n 1)
            echo "ipa_path=$IPA_PATH" >> $GITHUB_OUTPUT
      - uses: apple-actions/upload-testflight-build@v5
        with:
           app-path: ${{ steps.find_ipa.outputs.ipa_path }}
           issuer-id: ${{ vars.APP_STORE_CONNECT_ISSUER_ID }}
           api-key-id: ${{ vars.APP_STORE_CONNECT_API_KEY_ID }}
           api-private-key: ${{ vars.APP_STORE_CONNECT_API_PRIVATE_KEY }}