name: Build Layer

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
      platforms:
        type: string
        required: false
        default: ""
      full_version:
        type: string
        required: false
      base_version:
        type: string
        required: false
    outputs:
      web_path:
        value: ${{ jobs.build_web.outputs.path }}

jobs:
  build_web:
    if: contains(inputs.platforms, 'web')
    uses: ./.github/workflows/10-build-web.yml
    with:
      flavor: ${{ inputs.flavor }}
    secrets: inherit
