name: Build Layer

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
      platforms:
        type: string
        required: false
        default: ""
jobs:
  build_web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4