name: Check Platforms

on:
  workflow_call:
    outputs:
      android_exists:
        value: ${{ jobs.check.outputs.android_exists }}
      ios_exists:
        value: ${{ jobs.check.outputs.ios_exists }}
      windows_exists:
        value: ${{ jobs.check.outputs.windows_exists }}
      linux_exists:
        value: ${{ jobs.check.outputs.linux_exists }}
      macos_exists:
        value: ${{ jobs.check.outputs.macos_exists }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      android_exists: ${{ steps.check_android.outputs.exists }}
      ios_exists: ${{ steps.check_ios.outputs.exists }}
      windows_exists: ${{ steps.check_windows.outputs.exists }}
      linux_exists: ${{ steps.check_linux.outputs.exists }}
      macos_exists: ${{ steps.check_macos.outputs.exists }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - id: check_android
        run: |
          if [ -d "android" ]; then echo "exists=true" >> $GITHUB_OUTPUT; else echo "exists=false" >> $GITHUB_OUTPUT; fi
      - id: check_ios
        run: |
          if [ -d "ios" ]; then echo "exists=true" >> $GITHUB_OUTPUT; else echo "exists=false" >> $GITHUB_OUTPUT; fi
      - id: check_windows
        run: |
          if [ -d "windows" ]; then echo "exists=true" >> $GITHUB_OUTPUT; else echo "exists=false" >> $GITHUB_OUTPUT; fi
      - id: check_linux
        run: |
          if [ -d "linux" ]; then echo "exists=true" >> $GITHUB_OUTPUT; else echo "exists=false" >> $GITHUB_OUTPUT; fi
      - id: check_macos
        run: |
          if [ -d "macos" ]; then echo "exists=true" >> $GITHUB_OUTPUT; else echo "exists=false" >> $GITHUB_OUTPUT; fi
