name: Manual Firebase Distribution (Dev)
on:
  workflow_dispatch:
jobs:
  version:
    uses: ./.github/workflows/get-version.yml
  distribute:
    needs: version
    uses: ./.github/workflows/deploy-android-shorebird.yml
    with:
      flavor: dev
      full_version: ${{ needs.version.outputs.full_version }}
      base_version: ${{ needs.version.outputs.base_version }}
    secrets:
      SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
  firebase:
    needs: distribute
    if: always() && needs.distribute.result == 'success'
    uses: ./.github/workflows/build-firebase-apk.yml
    with:
      flavor: dev
    secrets:
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_ADMIN_SDK: ${{ secrets.FIREBASE_ADMIN_SDK }}
